---
- name: cloudflare
  color: "171515"
  description: >-
    Changes made in the cloudflare module
- name: ci
  color: "171515"
  description: >-
    Changes made in the ci directory
# Renovate
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/terraform
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"
