---
name-template: 'Draft'
tag-template: 'v1.0.0'
change-title-escapes: '\<*_&'
categories:
  - title: "ðŸš€ Features"
    label: "feat"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "fix"
  - title: "ðŸ§© Dependency Updates"
    collapse-after: 5
    labels:
      - "deps"
      - "dependencies"
      - "bump"
      - "chore"
  - title: 'ðŸ”¬ Others'
    labels:
      - 'style'
      - 'refactor'
      - 'test'
      - 'ci'
    collapse-after: 5
template: |
  ## Changes

  $CHANGES
