---
name-template: "Release v1.0.0"
tag-template: "v1.0.0"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
categories:
  - title: "AWS"
    labels: ["aws"]
  - title: "Cloudflare"
    labels: ["cloudflare"]
  - title: "Github"
    labels: ["github"]
version-resolver:
  major:
    labels: ["type/break"]
  minor:
    labels: ["type/major", "type/minor"]
  patch:
    labels: ["type/patch"]
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v1.0.0
