name: Generate Github App Token

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      token:
        description: "App token to use"
        value: ${{ jobs.generate-bot-token.outputs.token }}

jobs:
  generate-bot-token:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Token
        id: generate-token
        if: github.event_name == 'pull_request'
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
