---
name: Broken links checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Every day at 6am
  pull_request:
    branches: ["main"]

jobs:

  app-token:
    uses: ./.github/workflows/app-token.yaml
    secrets: inherit

  check:
    runs-on: ubuntu-latest
    needs:
      - app-token
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: "${{ needs.app-token.outputs.token }}"
        with:
          args: >
            --verbose
            --exclude-mail
            './**/*.md'

      - name: Find Broken links issues
        id: broken-link-check-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            broken-links

      - name: Update issues
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken links detected 🔗
          issue-number: "${{ steps.broken-link-check-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: "${{ needs.app-token.outputs.token }}"
          labels: |
            broken-links
