---
name: Broken links checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Every day at 6am
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          BOT_APP_ID: op://terraformars/github/app_id
          BOT_APP_PRIVATE_KEY: op://terraformars/github/app_private_key

      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: "${{ steps.load-secrets.outputs.BOT_APP_ID }}"
          private_key: "${{ steps.load-secrets.outputs.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          args: >
            --verbose
            --exclude-mail
            './**/*.md'

      - name: Find Broken links issues
        id: broken-link-check-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            broken-links

      - name: Update issues
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken links detected 🔗
          issue-number: "${{ steps.broken-link-check-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: "${{ steps.generate-token.outputs.token }}"
          labels: |
            broken-links
