---
name: Broken links checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Every day at 6am
  pull_request:
    branches: ["main"]

jobs:

  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: "${{ needs.app-token.outputs.token }}"
        with:
          args: >
            --verbose
            --exclude-mail
            './**/*.md'

      - name: Find Broken links issues
        id: broken-link-check-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            broken-links


      - name: Update issues
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken links detected 🔗
          issue-number: "${{ steps.broken-link-check-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: "${{ steps.generate-token.outputs.token }}"
          labels: |
            broken-links
