---
name: Pull Request Labeler

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:

  labeler:
    runs-on: ubuntu-22.04
    steps:
      - name : Check out Git Repository
        uses: actions/checkout@v3

      - name: Labeler
        uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4.2.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ steps.generate-token.outputs.token }}"
