---
name: Pull Request Labeler

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          BOT_APP_ID: op://terraformars/github/app_id
          BOT_APP_PRIVATE_KEY: op://terraformars/github/app_private_key

      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: "${{ steps.load-secrets.outputs.BOT_APP_ID }}"
          private_key: "${{ steps.load-secrets.outputs.BOT_APP_PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@v4.2.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ steps.generate-token.outputs.token }}"
