---
name: Pull Request Labeler

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:

  app-token:
    uses: ./.github/workflows/app-token.yaml
    secrets: inherit

  labeler:
    runs-on: ubuntu-latest
    needs:
      - app-token
    steps:
      - name: Labeler
        uses: actions/labeler@v4.2.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ needs.app-token.outputs.token }}"
