---
name: "Draft Release"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:

  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Prepare release draft
        uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.25.0
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
