---
name: "Draft Release"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read

jobs:

  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Prepare release draft
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          commitish: main
          config-name: release-drafter.yaml
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
