---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry Run"
        default: "false"
        required: false
      logLevel:
        description: "Override default log level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  push:
    branches:
      - "main"
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Validate Renovate JSON
        run: jq type .github/renovate.json5

      - name: Override default config with input variables
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN}}" >> $GITHUB_ENV
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.logLevel || env.LOG_LEVEL}}" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@76d49712364696a06b60e8647df46b288fff0ddc # v40.2.4
        with:
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.app-generate.outputs.token }}"
