---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry Run"
        default: "false"
        required: false
      logLevel:
        description: "Override default log level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  push:
    branches:
      - "main"
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Validate Renovate JSON
        run: jq type .github/renovate.json5

      - name: Override default config with input variables
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN}}" >> $GITHUB_ENV
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.logLevel || env.LOG_LEVEL}}" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@23a02fe7be9e93f857a953cc8162e57d2c8401ef # v39.0.1
        with:
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.app-generate.outputs.token }}"
