---
name: Sync PR labels

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/labels.yaml"]



jobs:
  app-token:
    uses: ./.github/workflows/app-token.yaml
    secrets: inherit

  labels:
    name: Sync PR Labels
    needs:
      - app-token
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Sync Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # renovate: tag=v2.3.2
        with:
          config-file: .github/labels.yaml
          token: "${{ needs.app-token.outputs.token }}"
          delete-other-labels: true
