name: tflint

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  tflint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - uses: terraform-linters/setup-tflint@ba6bb2989f94daf58a4cc6eac2c1ca7398a678bf # v3
        name: Setup TFLint
        with:
          github_token: "${{ steps.generate-token.outputs.token }}"

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

        # --force continue with workflow when an error raises
      - name: Run TFLint
        run: tflint -f compact --recursive
