name: tflint

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  tflint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - uses: terraform-linters/setup-tflint@a5a1af8c6551fb10c53f1cd4ba62359f1973746f # v3
        name: Setup TFLint
        with:
          github_token: "${{ steps.generate-token.outputs.token }}"

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

        # --force continue with workflow when an error raises
      - name: Run TFLint
        run: tflint -f compact --recursive
