name: tfsec

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif
          args: |
            --force-all-dirs
            --verbose
            --debug
            --config-file=${GITHUB_WORKSPACE}.tfsec.yaml

      - name: Run tfsec
        run: |
          cat tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
